/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform */
        get: operations["platform_api_platform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_sym_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_sym_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/universes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universes */
        get: operations["universes_api_sym_universes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/return-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return Windows */
        get: operations["return_windows_api_sym_return_windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/universes/{universe_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_sym_universes__universe_id__heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Securities */
        get: operations["securities_api_sym_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/securities/{figi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security Detail */
        get: operations["security_detail_api_sym_securities__figi__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attention */
        get: operations["attention_api_sym_attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation */
        get: operations["validation_api_sym_validation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_api_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_portfolios_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_portfolios_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_portfolios__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Weights */
        post: operations["upload_weights_api_portfolios__pid__weights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Returns */
        get: operations["portfolio_returns_api_portfolios__pid__returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Benchmarks */
        get: operations["list_benchmarks_api_analytics_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Analytics */
        get: operations["portfolio_analytics_api_portfolios__pid__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops */
        get: operations["list_ops_api_operate_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_operate_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_operate_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Op */
        post: operations["run_op_api_operate_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Series */
        get: operations["list_series_api_macro_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Series */
        get: operations["get_series_api_macro_series__series_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signal/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factors */
        get: operations["list_factors_api_signal_factors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signal/factors/{factor_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Factor Ranking */
        get: operations["factor_ranking_api_signal_factors__factor_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backtest Ep */
        post: operations["run_backtest_ep_api_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_backtest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_backtest_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimiser/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve Ep */
        post: operations["solve_ep_api_optimiser_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimiser/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Solutions */
        get: operations["list_solutions_api_optimiser_solutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimiser/solutions/{solution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solution */
        get: operations["get_solution_api_optimiser_solutions__solution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/altdata/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Series */
        get: operations["list_series_api_altdata_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/altdata/series/{figi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Series */
        get: operations["get_series_api_altdata_series__figi__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AltObservation */
        AltObservation: {
            /** Date */
            date: string;
            /** Views */
            views: number;
        };
        /** AltSeries */
        AltSeries: {
            /** Composite Figi */
            composite_figi: string;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string | null;
            /** Article */
            article: string;
            /** N Obs */
            n_obs: number;
            /** Last */
            last: string | null;
            /** Latest Views */
            latest_views: number | null;
            /** Avg7 */
            avg7: number | null;
            /** Avg30 */
            avg30: number | null;
            /** Attention Spike */
            attention_spike: number | null;
        };
        /** AltSeriesDetail */
        AltSeriesDetail: {
            /** Composite Figi */
            composite_figi: string;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string | null;
            /** Article */
            article: string;
            /** Observations */
            observations: components["schemas"]["AltObservation"][];
        };
        /** Analytics */
        Analytics: {
            /** As Of */
            as_of: string | null;
            /** Window */
            window: string;
            benchmark: components["schemas"]["Benchmark"] | null;
            /** Portfolio Currencies */
            portfolio_currencies: string[];
            /** N Days */
            n_days: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            metrics: components["schemas"]["Metrics"] | null;
            /** Warning */
            warning: string | null;
        };
        /** BacktestRunRequest */
        BacktestRunRequest: {
            /**
             * Factor
             * @default mom_12_1
             */
            factor: string;
            /**
             * Universe
             * @default sp500
             */
            universe: string;
            /**
             * Top Pct
             * @default 0.2
             */
            top_pct: number;
        };
        /** BacktestRunResult */
        BacktestRunResult: {
            /** Ok */
            ok: boolean;
            /** Run Id */
            run_id?: number | null;
            /** Error */
            error?: string | null;
        };
        /** Benchmark */
        Benchmark: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Currency */
            currency: string | null;
        };
        /** Client */
        Client: {
            /** Client Id */
            client_id: number;
            /** Name */
            name: string;
            /** Created At */
            created_at: string | null;
            /** N Portfolios */
            n_portfolios: number;
        };
        /** CreateClient */
        CreateClient: {
            /** Name */
            name: string;
        };
        /** CreatePortfolio */
        CreatePortfolio: {
            /** Name */
            name: string;
            /**
             * Client
             * @default
             */
            client: string;
            /**
             * Base Currency
             * @default USD
             */
            base_currency: string;
        };
        /** CreatedClient */
        CreatedClient: {
            /** Client Id */
            client_id: number;
        };
        /** CreatedPortfolio */
        CreatedPortfolio: {
            /** Portfolio Id */
            portfolio_id: number;
        };
        /** CurvePoint */
        CurvePoint: {
            /** Date */
            date: string;
            /** Strat */
            strat: number;
            /** Base */
            base: number;
        };
        /** FactorConstituent */
        FactorConstituent: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Raw */
            raw: number;
            /** Zscore */
            zscore: number | null;
            /** Rank */
            rank: number;
            /** Pctile */
            pctile: number | null;
        };
        /** FactorRanking */
        FactorRanking: {
            /** Factor Key */
            factor_key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Direction */
            direction: string;
            /** Universe Id */
            universe_id: string;
            /** As Of */
            as_of: string | null;
            /** Bottom */
            bottom: boolean;
            /** Constituents */
            constituents: components["schemas"]["FactorConstituent"][];
        };
        /** FactorSummary */
        FactorSummary: {
            /** Factor Key */
            factor_key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Direction */
            direction: string;
            /** Universes */
            universes: number;
            /** Scores */
            scores: number;
            /** As Of */
            as_of: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Job Id */
            job_id: number;
            /** Op */
            op: string;
            /** Args */
            args: string[];
            /** Status */
            status: string;
            /** Exit Code */
            exit_code: number | null;
            /** Output */
            output: string | null;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** Metrics */
        Metrics: {
            /** Ann Return */
            ann_return: number | null;
            /** Ann Vol */
            ann_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Beta */
            beta: number | null;
            /** Alpha Ann */
            alpha_ann: number | null;
            /** Correlation */
            correlation: number | null;
            /** Bench Ann Return */
            bench_ann_return: number | null;
            /** Bench Ann Vol */
            bench_ann_vol: number | null;
            /** Bench Sharpe */
            bench_sharpe: number | null;
            /** Active Return */
            active_return: number | null;
            /** Tracking Error */
            tracking_error: number | null;
            /** Information Ratio */
            information_ratio: number | null;
            /** Hit Ratio */
            hit_ratio: number | null;
            /** Batting Average */
            batting_average: number | null;
            /** Slugging Ratio */
            slugging_ratio: number | null;
        };
        /** Observation */
        Observation: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /** OpDef */
        OpDef: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Writes */
            writes: boolean;
            /** Takes Universe */
            takes_universe: boolean;
            /** Note */
            note: string;
        };
        /** OptSolutionDetail */
        OptSolutionDetail: {
            /** Solution Id */
            solution_id: number;
            /** Created At */
            created_at: string | null;
            /** Universe Id */
            universe_id: string;
            /** Method */
            method: string;
            /** N Assets */
            n_assets: number;
            /** Lookback Days */
            lookback_days: number;
            /** Exp Return */
            exp_return: number | null;
            /** Exp Vol */
            exp_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Ew Vol */
            ew_vol: number | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /**
             * Weights
             * @default []
             */
            weights: components["schemas"]["OptWeight"][];
        };
        /** OptSolutionSummary */
        OptSolutionSummary: {
            /** Solution Id */
            solution_id: number;
            /** Created At */
            created_at: string | null;
            /** Universe Id */
            universe_id: string;
            /** Method */
            method: string;
            /** N Assets */
            n_assets: number;
            /** Lookback Days */
            lookback_days: number;
            /** Exp Return */
            exp_return: number | null;
            /** Exp Vol */
            exp_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Ew Vol */
            ew_vol: number | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
        };
        /** OptSolveRequest */
        OptSolveRequest: {
            /**
             * Universe
             * @default sp500
             */
            universe: string;
            /**
             * Method
             * @default min_variance
             */
            method: string;
            /**
             * N
             * @default 40
             */
            n: number;
            /**
             * Lookback
             * @default 252
             */
            lookback: number;
        };
        /** OptSolveResult */
        OptSolveResult: {
            /** Ok */
            ok: boolean;
            /** Solution Id */
            solution_id?: number | null;
            /** Error */
            error?: string | null;
        };
        /** OptWeight */
        OptWeight: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string | null;
            /** Weight */
            weight: number;
        };
        /** PortfolioDetail */
        PortfolioDetail: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Base Currency */
            base_currency: string;
            /** Created At */
            created_at: string | null;
            /** As Of Dates */
            as_of_dates: string[];
            /** Latest As Of */
            latest_as_of: string | null;
            /** Weights */
            weights: components["schemas"]["Weight"][];
        };
        /** PortfolioReturns */
        PortfolioReturns: {
            /** Window */
            window: string;
            /** As Of */
            as_of: string | null;
            /** N Constituents */
            n_constituents: number;
            /** N With Return */
            n_with_return: number;
            /** Total Weight */
            total_weight: number;
            /** Covered Weight */
            covered_weight: number;
            /** Portfolio Return */
            portfolio_return: number | null;
            /** Portfolio Return Normalized */
            portfolio_return_normalized: number | null;
            /** Constituents */
            constituents: components["schemas"]["RetConstituent"][];
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Base Currency */
            base_currency: string;
            /** Created At */
            created_at: string | null;
            /** N Weights */
            n_weights: number;
            /** Latest As Of */
            latest_as_of: string | null;
        };
        /** RetConstituent */
        RetConstituent: {
            /** Ticker */
            ticker: string;
            /** Weight */
            weight: number;
            /** Ret */
            ret: number | null;
            /** Contribution */
            contribution: number | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: number;
            /** Created At */
            created_at: string | null;
            /** Factor */
            factor: string;
            /** Universe Id */
            universe_id: string;
            /** Top Pct */
            top_pct: number;
            /** Rebalance */
            rebalance: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** N Days */
            n_days: number | null;
            /** N Rebalances */
            n_rebalances: number | null;
            summary: components["schemas"]["Summary"] | null;
            /**
             * Curve
             * @default []
             */
            curve: components["schemas"]["CurvePoint"][];
        };
        /** RunRequest */
        RunRequest: {
            /** Op */
            op: string;
            /**
             * Args
             * @default []
             */
            args: string[];
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** RunResult */
        RunResult: {
            /** Ok */
            ok: boolean;
            /** Job Id */
            job_id?: number | null;
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: number;
            /** Created At */
            created_at: string | null;
            /** Factor */
            factor: string;
            /** Universe Id */
            universe_id: string;
            /** Top Pct */
            top_pct: number;
            /** Rebalance */
            rebalance: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** N Days */
            n_days: number | null;
            /** N Rebalances */
            n_rebalances: number | null;
            summary: components["schemas"]["Summary"] | null;
        };
        /** SeriesDetail */
        SeriesDetail: {
            /** Series Id */
            series_id: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /** Geo */
            geo: string | null;
            /** Unit */
            unit: string | null;
            /** Frequency */
            frequency: string | null;
            /** Observations */
            observations: components["schemas"]["Observation"][];
        };
        /** SeriesSummary */
        SeriesSummary: {
            /** Series Id */
            series_id: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /** Geo */
            geo: string | null;
            /** Unit */
            unit: string | null;
            /** Frequency */
            frequency: string | null;
            /** N Obs */
            n_obs: number;
            /** First */
            first: string | null;
            /** Last */
            last: string | null;
            /** Latest */
            latest: number | null;
        };
        /** Stats */
        Stats: {
            /** Total Return */
            total_return?: number | null;
            /** Ann Return */
            ann_return?: number | null;
            /** Ann Vol */
            ann_vol?: number | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
        };
        /** Summary */
        Summary: {
            strategy: components["schemas"]["Stats"];
            baseline: components["schemas"]["Stats"];
            /** Excess Total */
            excess_total?: number | null;
            /** First Rebalance */
            first_rebalance?: string | null;
            /** First Holding N */
            first_holding_n?: number | null;
        };
        /** UploadResult */
        UploadResult: {
            /** Stored */
            stored: number;
            /** Unresolved */
            unresolved: string[];
            /** As Of */
            as_of: string;
        };
        /** UploadWeights */
        UploadWeights: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Items */
            items: components["schemas"]["WeightItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Weight */
        Weight: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Weight */
            weight: number;
        };
        /** WeightItem */
        WeightItem: {
            /** Identifier */
            identifier: string;
            /** Weight */
            weight: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    platform_api_platform_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_sym_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    overview_api_sym_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    universes_api_sym_universes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    return_windows_api_sym_return_windows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    heatmap_api_sym_universes__universe_id__heatmap_get: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    securities_api_sym_securities_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    security_detail_api_sym_securities__figi__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                figi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attention_api_sym_attention_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    validation_api_sym_validation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_portfolios_api_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"][];
                };
            };
        };
    };
    create_portfolio_api_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortfolio"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedPortfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_portfolios_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    create_client_api_portfolios_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClient"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedClient"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_portfolios__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_weights_api_portfolios__pid__weights_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadWeights"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_returns_api_portfolios__pid__returns_get: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioReturns"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_benchmarks_api_analytics_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Benchmark"][];
                };
            };
        };
    };
    portfolio_analytics_api_portfolios__pid__analytics_get: {
        parameters: {
            query: {
                /** @description instrument sym_id of the index benchmark */
                benchmark: number;
                /** @description ALL | YTD | 1M | 3M | 6M | 1Y | 2Y | 3Y */
                window?: string;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops_api_operate_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpDef"][];
                };
            };
        };
    };
    list_jobs_api_operate_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_operate_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_op_api_operate_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_api_macro_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesSummary"][];
                };
            };
        };
    };
    get_series_api_macro_series__series_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_factors_api_signal_factors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorSummary"][];
                };
            };
        };
    };
    factor_ranking_api_signal_factors__factor_key__get: {
        parameters: {
            query: {
                /** @description universe_id, e.g. sp500 | ibov | ibx */
                universe: string;
                limit?: number;
                /** @description show least-favourable end instead of top */
                bottom?: boolean;
            };
            header?: never;
            path: {
                factor_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorRanking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_ep_api_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_backtest_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run_api_backtest_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_ep_api_optimiser_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptSolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptSolveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_solutions_api_optimiser_solutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptSolutionSummary"][];
                };
            };
        };
    };
    get_solution_api_optimiser_solutions__solution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptSolutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_api_altdata_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltSeries"][];
                };
            };
        };
    };
    get_series_api_altdata_series__figi__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                figi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
