/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform */
        get: operations["platform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sym Health */
        get: operations["sym_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/universes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universes */
        get: operations["universes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/return-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return Windows */
        get: operations["return_windows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/universes/{universe_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Securities */
        get: operations["securities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/securities/{figi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security Detail */
        get: operations["security_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attention */
        get: operations["attention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sym/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation */
        get: operations["validation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients"];
        put?: never;
        /** Create Client */
        post: operations["create_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Weights */
        post: operations["upload_weights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{pid}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Returns */
        get: operations["portfolio_returns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Benchmarks */
        get: operations["list_benchmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/portfolios/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Analytics */
        get: operations["portfolio_analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ops */
        get: operations["list_ops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline History
         * @description Recent sym pipeline runs (FR-6) with qrp-job correlation via triggered_by.
         */
        get: operations["pipeline_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Op */
        post: operations["run_op"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Macro Series */
        get: operations["list_macro_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/macro/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Macro Series */
        get: operations["get_macro_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factors */
        get: operations["list_factors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/factors/{factor_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Factor Ranking */
        get: operations["factor_ranking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backtest Ep */
        post: operations["run_backtest_ep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimiser/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve Ep */
        post: operations["solve_ep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimiser/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Solutions */
        get: operations["list_solutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimiser/solutions/{solution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solution */
        get: operations["get_solution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/altdata/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Altdata Series */
        get: operations["list_altdata_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/altdata/series/{figi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Altdata Series */
        get: operations["get_altdata_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lineage/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph
         * @description Table-level lineage edges (declared + auto-derived + FK referential) with group + stats.
         */
        get: operations["graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lineage/field-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Field Flow
         * @description Mermaid `flowchart` source for each join key's propagation (composite_figi, sym_id).
         */
        get: operations["field_flow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AltObservation */
        AltObservation: {
            /** Obs Date */
            obs_date: string;
            /** Views */
            views: number;
        };
        /** AltSeries */
        AltSeries: {
            /** Composite Figi */
            composite_figi: string;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string | null;
            /** Article */
            article: string;
            /** N Obs */
            n_obs: number;
            /** As Of Date */
            as_of_date: string | null;
            /** Latest Views */
            latest_views: number | null;
            /** Avg7 */
            avg7: number | null;
            /** Avg30 */
            avg30: number | null;
            /** Attention Spike */
            attention_spike: number | null;
        };
        /** AltSeriesDetail */
        AltSeriesDetail: {
            /** Composite Figi */
            composite_figi: string;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string | null;
            /** Article */
            article: string;
            /** Observations */
            observations: components["schemas"]["AltObservation"][];
        };
        /** Analytics */
        Analytics: {
            /** As Of Date */
            as_of_date: string | null;
            /** Window */
            window: string;
            benchmark: components["schemas"]["Benchmark"] | null;
            /** Portfolio Currencies */
            portfolio_currencies: string[];
            /** N Days */
            n_days: number;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            metrics: components["schemas"]["Metrics"] | null;
            /** Warning */
            warning: string | null;
        };
        /** Attention */
        Attention: {
            /** Review Queue */
            review_queue: components["schemas"]["ReviewItem"][];
            price_gaps: components["schemas"]["PriceGaps"];
            /** Membership Proposals */
            membership_proposals: components["schemas"]["MembershipProposal"][];
        };
        /** BacktestRunRequest */
        BacktestRunRequest: {
            /**
             * Factor
             * @default mom_12_1
             */
            factor: string;
            /**
             * Universe
             * @default sp500
             */
            universe: string;
            /**
             * Top Pct
             * @default 0.2
             */
            top_pct: number;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Save Portfolio
             * @default false
             */
            save_portfolio: boolean;
        };
        /** BacktestRunResult */
        BacktestRunResult: {
            /** Ok */
            ok: boolean;
            /** Run Id */
            run_id?: number | null;
            /** Portfolio Id */
            portfolio_id?: number | null;
            /** Error */
            error?: string | null;
        };
        /** Benchmark */
        Benchmark: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Currency */
            currency: string | null;
        };
        /** Client */
        Client: {
            /** Client Id */
            client_id: number;
            /** Name */
            name: string;
            /** Created At */
            created_at: string | null;
            /** N Portfolios */
            n_portfolios: number;
        };
        /** CreateClient */
        CreateClient: {
            /** Name */
            name: string;
        };
        /** CreatePortfolio */
        CreatePortfolio: {
            /** Name */
            name: string;
            /**
             * Client
             * @default
             */
            client: string;
            /**
             * Base Currency
             * @default USD
             */
            base_currency: string;
        };
        /** CreatedClient */
        CreatedClient: {
            /** Client Id */
            client_id: number;
        };
        /** CreatedPortfolio */
        CreatedPortfolio: {
            /** Portfolio Id */
            portfolio_id: number;
        };
        /** CurvePoint */
        CurvePoint: {
            /** Obs Date */
            obs_date: string;
            /** Strat */
            strat: number;
            /** Base */
            base: number;
        };
        /** FactorConstituent */
        FactorConstituent: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Raw */
            raw: number;
            /** Zscore */
            zscore: number | null;
            /** Rank */
            rank: number;
            /** Pctile */
            pctile: number | null;
        };
        /** FactorRanking */
        FactorRanking: {
            /** Factor Key */
            factor_key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Direction */
            direction: string;
            /** Universe Id */
            universe_id: string;
            /** As Of Date */
            as_of_date: string | null;
            /** Bottom */
            bottom: boolean;
            /** Constituents */
            constituents: components["schemas"]["FactorConstituent"][];
        };
        /** FactorSummary */
        FactorSummary: {
            /** Factor Key */
            factor_key: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Direction */
            direction: string;
            /** Universes */
            universes: number;
            /** Scores */
            scores: number;
            /** As Of Date */
            as_of_date: string | null;
        };
        /** FieldFlow */
        FieldFlow: {
            /** Key */
            key: string;
            /** Mermaid */
            mermaid: string;
        };
        /** FieldFlows */
        FieldFlows: {
            /** Flows */
            flows: components["schemas"]["FieldFlow"][];
            /** Dagster Url */
            dagster_url: string;
        };
        /** FreshnessItem */
        FreshnessItem: {
            /** Area */
            area: string;
            /** As Of Date */
            as_of_date: string | null;
            /** Days Behind */
            days_behind: number | null;
            /** Status */
            status: string;
        };
        /** FundamentalsInfo */
        FundamentalsInfo: {
            /** Market Cap Lcy */
            market_cap_lcy: number | null;
            /** Market Cap Usd */
            market_cap_usd: number | null;
            /** Shares Outstanding */
            shares_outstanding: number | null;
            /** Currency */
            currency: string | null;
            /** As Of Date */
            as_of_date: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Platform */
            platform: string;
            /** Modules */
            modules: string[];
        };
        /** Heatmap */
        Heatmap: {
            /** Universe Id */
            universe_id: string;
            /** Universe Name */
            universe_name: string | null;
            /** Window */
            window: string;
            /** Members Resolved */
            members_resolved: number;
            /** Shown */
            shown: number;
            /** Missing Mcap */
            missing_mcap: number;
            /** Merged Share Classes */
            merged_share_classes: number;
            /** Cells */
            cells: components["schemas"]["HeatmapCell"][];
        };
        /** HeatmapCell */
        HeatmapCell: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Market Cap Usd */
            market_cap_usd: number;
            /** Market Cap Lcy */
            market_cap_lcy: number | null;
            /** Currency */
            currency: string | null;
            /** Price */
            price: number | null;
            /** Ret */
            ret: number | null;
        };
        /** Job */
        Job: {
            /** Job Id */
            job_id: number;
            /** Op */
            op: string;
            /** Args */
            args: string[];
            /** Status */
            status: string;
            /** Exit Code */
            exit_code: number | null;
            /** Output */
            output: string | null;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Heartbeat At */
            heartbeat_at: string | null;
        };
        /** LastRun */
        LastRun: {
            /** Run Id */
            run_id: string | null;
            /** Mode */
            mode: string | null;
            /** Status */
            status: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Rows Written */
            rows_written: number | null;
        };
        /** LineageEdge */
        LineageEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Basis */
            basis: string;
            /** Source Group */
            source_group?: string | null;
            /** Target Group */
            target_group?: string | null;
        };
        /** LineageGraph */
        LineageGraph: {
            /** Edges */
            edges: components["schemas"]["LineageEdge"][];
            stats: components["schemas"]["LineageStats"];
            /** Dagster Url */
            dagster_url: string;
        };
        /** LineageStats */
        LineageStats: {
            /** Assets */
            assets: number;
            /** Edges */
            edges: number;
            /** By Basis */
            by_basis: {
                [key: string]: number;
            };
        };
        /** MembershipProposal */
        MembershipProposal: {
            /** Proposal Id */
            proposal_id: string;
            /** Universe Id */
            universe_id: string | null;
            /** Raw Identifier */
            raw_identifier: string | null;
            /** Change */
            change: string | null;
            /** Status */
            status: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** Metrics */
        Metrics: {
            /** Ann Return */
            ann_return: number | null;
            /** Ann Vol */
            ann_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Beta */
            beta: number | null;
            /** Alpha Ann */
            alpha_ann: number | null;
            /** Correlation */
            correlation: number | null;
            /** Bench Ann Return */
            bench_ann_return: number | null;
            /** Bench Ann Vol */
            bench_ann_vol: number | null;
            /** Bench Sharpe */
            bench_sharpe: number | null;
            /** Active Return */
            active_return: number | null;
            /** Tracking Error */
            tracking_error: number | null;
            /** Information Ratio */
            information_ratio: number | null;
            /** Hit Ratio */
            hit_ratio: number | null;
            /** Batting Average */
            batting_average: number | null;
            /** Slugging Ratio */
            slugging_ratio: number | null;
        };
        /** ModuleInfo */
        ModuleInfo: {
            /** Key */
            key: string;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** Observation */
        Observation: {
            /** Obs Date */
            obs_date: string;
            /** Value */
            value: number;
        };
        /** OpDef */
        OpDef: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Writes */
            writes: boolean;
            /** Takes Universe */
            takes_universe: boolean;
            /** Takes Scope */
            takes_scope: boolean;
            /** Note */
            note: string;
        };
        /** OptSolutionDetail */
        OptSolutionDetail: {
            /** Solution Id */
            solution_id: number;
            /** Created At */
            created_at: string | null;
            /** Universe Id */
            universe_id: string;
            /** Method */
            method: string;
            /** N Assets */
            n_assets: number;
            /** Lookback Days */
            lookback_days: number;
            /** Exp Return */
            exp_return: number | null;
            /** Exp Vol */
            exp_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Ew Vol */
            ew_vol: number | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /**
             * Weights
             * @default []
             */
            weights: components["schemas"]["OptWeight"][];
        };
        /** OptSolutionSummary */
        OptSolutionSummary: {
            /** Solution Id */
            solution_id: number;
            /** Created At */
            created_at: string | null;
            /** Universe Id */
            universe_id: string;
            /** Method */
            method: string;
            /** N Assets */
            n_assets: number;
            /** Lookback Days */
            lookback_days: number;
            /** Exp Return */
            exp_return: number | null;
            /** Exp Vol */
            exp_vol: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Ew Vol */
            ew_vol: number | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
        };
        /** OptSolveRequest */
        OptSolveRequest: {
            /**
             * Universe
             * @default sp500
             */
            universe: string;
            /**
             * Method
             * @default min_variance
             */
            method: string;
            /**
             * N
             * @default 40
             */
            n: number;
            /**
             * Lookback
             * @default 252
             */
            lookback: number;
        };
        /** OptSolveResult */
        OptSolveResult: {
            /** Ok */
            ok: boolean;
            /** Solution Id */
            solution_id?: number | null;
            /** Error */
            error?: string | null;
        };
        /** OptWeight */
        OptWeight: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string | null;
            /** Weight */
            weight: number;
        };
        /** PlatformResponse */
        PlatformResponse: {
            /** Name */
            name: string;
            /** Tagline */
            tagline: string | null;
            /** Theme */
            theme: string;
            /** Modules */
            modules: components["schemas"]["ModuleInfo"][];
        };
        /** PortfolioDetail */
        PortfolioDetail: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Base Currency */
            base_currency: string;
            /** Created At */
            created_at: string | null;
            /** As Of Dates */
            as_of_dates: string[];
            /** Latest As Of Date */
            latest_as_of_date: string | null;
            /** Weights */
            weights: components["schemas"]["Weight"][];
        };
        /** PortfolioReturns */
        PortfolioReturns: {
            /** Window */
            window: string;
            /** As Of Date */
            as_of_date: string | null;
            /** Returns As Of Date */
            returns_as_of_date?: string | null;
            /** N Constituents */
            n_constituents: number;
            /** N With Return */
            n_with_return: number;
            /** Total Weight */
            total_weight: number;
            /** Covered Weight */
            covered_weight: number;
            /** Portfolio Return */
            portfolio_return: number | null;
            /** Portfolio Return Normalized */
            portfolio_return_normalized: number | null;
            /** Constituents */
            constituents: components["schemas"]["RetConstituent"][];
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Name */
            name: string;
            /** Client */
            client: string;
            /** Base Currency */
            base_currency: string;
            /** Created At */
            created_at: string | null;
            /** N Weights */
            n_weights: number;
            /** Latest As Of Date */
            latest_as_of_date: string | null;
        };
        /** PriceGap */
        PriceGap: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string | null;
            /** Session Date */
            session_date: string | null;
            /** Source */
            source: string | null;
            /** Detected At */
            detected_at: string | null;
        };
        /** PriceGaps */
        PriceGaps: {
            /** Total */
            total: number;
            /** Recent */
            recent: components["schemas"]["PriceGap"][];
        };
        /** PriceInfo */
        PriceInfo: {
            /** Close */
            close: number | null;
            /** Session Date */
            session_date: string | null;
        };
        /** RetConstituent */
        RetConstituent: {
            /** Ticker */
            ticker: string;
            /** Weight */
            weight: number;
            /** Ret */
            ret: number | null;
            /** Contribution */
            contribution: number | null;
        };
        /** ReturnWindow */
        ReturnWindow: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Review Id */
            review_id: string;
            /** Source Key */
            source_key: string | null;
            /** Source Input */
            source_input: string | null;
            /** Status */
            status: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: number;
            /** Created At */
            created_at: string | null;
            /** Factor */
            factor: string;
            /** Universe Id */
            universe_id: string;
            /** Top Pct */
            top_pct: number;
            /** Rebalance */
            rebalance: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** N Days */
            n_days: number | null;
            /** N Rebalances */
            n_rebalances: number | null;
            summary: components["schemas"]["Summary"] | null;
            /**
             * Curve
             * @default []
             */
            curve: components["schemas"]["CurvePoint"][];
        };
        /** RunHistoryRow */
        RunHistoryRow: {
            /** Run Id */
            run_id: number;
            /** Mode */
            mode: string;
            /** Source */
            source: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Attempted */
            attempted: number;
            /** Loaded */
            loaded: number;
            /** Skipped */
            skipped: number;
            /** Errored */
            errored: number;
            /** Rows Written */
            rows_written: number;
            /** Status */
            status: string;
            /** Triggered By */
            triggered_by: string | null;
        };
        /** RunRequest */
        RunRequest: {
            /** Op */
            op: string;
            /**
             * Args
             * @default []
             */
            args: string[];
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /** RunResult */
        RunResult: {
            /** Ok */
            ok: boolean;
            /** Job Id */
            job_id?: number | null;
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: number;
            /** Created At */
            created_at: string | null;
            /** Factor */
            factor: string;
            /** Universe Id */
            universe_id: string;
            /** Top Pct */
            top_pct: number;
            /** Rebalance */
            rebalance: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** N Days */
            n_days: number | null;
            /** N Rebalances */
            n_rebalances: number | null;
            summary: components["schemas"]["Summary"] | null;
        };
        /** SecuritiesPage */
        SecuritiesPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["SecurityRow"][];
        };
        /** SecurityDetail */
        SecurityDetail: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Mic */
            mic: string | null;
            /** Currency */
            currency: string | null;
            /** Status */
            status: string | null;
            /** Delist Date */
            delist_date: string | null;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Sub Industry */
            sub_industry: string | null;
            price: components["schemas"]["PriceInfo"];
            fundamentals: components["schemas"]["FundamentalsInfo"] | null;
            /** Returns */
            returns: components["schemas"]["WindowReturn"][];
        };
        /** SecurityRow */
        SecurityRow: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Mic */
            mic: string | null;
            /** Currency */
            currency: string | null;
            /** Status */
            status: string | null;
        };
        /** SeriesDetail */
        SeriesDetail: {
            /** Series Id */
            series_id: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /** Geo */
            geo: string | null;
            /** Unit */
            unit: string | null;
            /** Frequency */
            frequency: string | null;
            /** Observations */
            observations: components["schemas"]["Observation"][];
        };
        /** SeriesSummary */
        SeriesSummary: {
            /** Series Id */
            series_id: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /** Geo */
            geo: string | null;
            /** Unit */
            unit: string | null;
            /** Frequency */
            frequency: string | null;
            /** N Obs */
            n_obs: number;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Latest */
            latest: number | null;
        };
        /** Stats */
        Stats: {
            /** Total Return */
            total_return?: number | null;
            /** Ann Return */
            ann_return?: number | null;
            /** Ann Vol */
            ann_vol?: number | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
        };
        /** Summary */
        Summary: {
            strategy: components["schemas"]["Stats"];
            baseline: components["schemas"]["Stats"];
            /** Excess Total */
            excess_total?: number | null;
            /** First Rebalance */
            first_rebalance?: string | null;
            /** First Holding N */
            first_holding_n?: number | null;
        };
        /** SymHealth */
        SymHealth: {
            /** Module */
            module: string;
            /** Healthy */
            healthy: boolean;
        };
        /** SymOverview */
        SymOverview: {
            /** Securities */
            securities: number;
            /** Universes */
            universes: number;
            /** Priced Securities */
            priced_securities: number;
            /** Latest Session */
            latest_session: string | null;
            /** Freshness */
            freshness: components["schemas"]["FreshnessItem"][];
            last_run: components["schemas"]["LastRun"] | null;
        };
        /** UniverseSummary */
        UniverseSummary: {
            /** Universe Id */
            universe_id: string;
            /** Name */
            name: string | null;
            /** Members Resolved */
            members_resolved: number;
        };
        /** UploadResult */
        UploadResult: {
            /** Stored */
            stored: number;
            /** Unresolved */
            unresolved: string[];
            /** As Of Date */
            as_of_date: string;
        };
        /** UploadWeights */
        UploadWeights: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Items */
            items: components["schemas"]["WeightItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationRun */
        ValidationRun: {
            /** Run Id */
            run_id: string;
            /** Run At */
            run_at: string | null;
            /** Universe Id */
            universe_id: string | null;
            /** Checks */
            checks: number | null;
            /** Passed */
            passed: number | null;
            /** Warned */
            warned: number | null;
            /** Failed */
            failed: number | null;
            /** Status */
            status: string | null;
        };
        /** Weight */
        Weight: {
            /** Figi */
            figi: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string | null;
            /** Weight */
            weight: number;
        };
        /** WeightItem */
        WeightItem: {
            /** Identifier */
            identifier: string;
            /** Weight */
            weight: number;
        };
        /** WindowReturn */
        WindowReturn: {
            /** Code */
            code: string;
            /** Label */
            label: string | null;
            /** Pr */
            pr: number | null;
            /** Tr */
            tr: number | null;
            /** As Of Date */
            as_of_date: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    platform: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformResponse"];
                };
            };
        };
    };
    sym_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymHealth"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymOverview"];
                };
            };
        };
    };
    universes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseSummary"][];
                };
            };
        };
    };
    return_windows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnWindow"][];
                };
            };
        };
    };
    heatmap: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                universe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Heatmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    securities: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecuritiesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    security_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                figi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attention"];
                };
            };
        };
    };
    validation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"][];
                };
            };
        };
    };
    list_portfolios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"][];
                };
            };
        };
    };
    create_portfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortfolio"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedPortfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    create_client: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClient"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedClient"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_weights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadWeights"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_returns: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioReturns"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_benchmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Benchmark"][];
                };
            };
        };
    };
    portfolio_analytics: {
        parameters: {
            query: {
                /** @description instrument sym_id of the index benchmark */
                benchmark: number;
                /** @description ALL | YTD | 1M | 3M | 6M | 1Y | 2Y | 3Y */
                window?: string;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpDef"][];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_history: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_op: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_macro_series: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesSummary"][];
                };
            };
        };
    };
    get_macro_series: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_factors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorSummary"][];
                };
            };
        };
    };
    factor_ranking: {
        parameters: {
            query: {
                /** @description universe_id, e.g. sp500 | ibov | ibx */
                universe: string;
                limit?: number;
                /** @description show least-favourable end instead of top */
                bottom?: boolean;
            };
            header?: never;
            path: {
                factor_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorRanking"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_ep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_ep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptSolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptSolveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_solutions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptSolutionSummary"][];
                };
            };
        };
    };
    get_solution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptSolutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_altdata_series: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltSeries"][];
                };
            };
        };
    };
    get_altdata_series: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                figi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AltSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageGraph"];
                };
            };
        };
    };
    field_flow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldFlows"];
                };
            };
        };
    };
}
