"""AUTO-GENERATED by `lineage.generate` — do not hand-edit.
DERIVED: table-level + key-column lineage from downstream engines' captured SQL.
FK_REFERENTIAL: intra-DB referential edges from Postgres foreign keys.
"""

DERIVED = {
    'pageview': {'deps': ['security_symbology'], 'column_lineage': {'composite_figi': ['security_symbology']}},
    'point': {'deps': ['fact_returns', 'universe_membership'], 'column_lineage': {}},
    'run': {'deps': ['fact_returns', 'universe_membership'], 'column_lineage': {}},
    'score': {'deps': ['fact_returns', 'fundamentals', 'universe_membership'], 'column_lineage': {'composite_figi': ['fact_returns', 'fundamentals', 'universe_membership']}},
    'solution': {'deps': ['fact_returns', 'fundamentals', 'security_symbology', 'universe_membership'], 'column_lineage': {}},
    'weight': {'deps': ['fact_returns', 'fundamentals', 'security_symbology', 'universe_membership'], 'column_lineage': {'composite_figi': ['fact_returns', 'fundamentals', 'security_symbology', 'universe_membership']}},
    'wiki_map': {'deps': ['security_symbology'], 'column_lineage': {'composite_figi': ['security_symbology']}},
}

FK_REFERENTIAL = {
    'fact_index_returns': ['instrument'],
    'fact_returns': ['securities'],
    'fundamentals': ['securities'],
    'gics_scd': ['securities'],
    'index_levels': ['instrument'],
    'membership_event': ['universe'],
    'observation': ['series'],
    'pageview': ['wiki_map'],
    'point': ['run'],
    'portfolio_weight': ['portfolio'],
    'prices_raw': ['securities'],
    'score': ['factor'],
    'security_names': ['securities'],
    'security_symbology': ['securities'],
    'universe_member_resolution': ['universe'],
    'universe_membership': ['universe'],
    'weight': ['solution'],
}
