"""Generate a free Mermaid field-flow diagram for the warehouse join keys.

The interactive cross-asset *column*-lineage view is a Dagster+ feature. This renders the same
information for the two join keys (``composite_figi``, ``sym_id``) as a standalone Mermaid
flowchart that any Markdown renderer (GitHub, VS Code, the docs site) shows — no subscription.

It reads the final, merged table-level edge list from :mod:`lineage.assets` (declared + auto-derived
+ FK referential) and keeps only edges between tables that actually carry the key.

Run: ``uv run python -m lineage.diagram`` → writes ``packages/lineage/docs/field-flow.md``.
"""

from __future__ import annotations

import re
from pathlib import Path

from .assets import edges, key_tables

_KEYS = ["composite_figi", "sym_id"]


def _node(table: str) -> str:
    return re.sub(r"[^0-9A-Za-z_]", "_", table)  # Mermaid-safe node id


def flowchart(key: str) -> str:
    """A Mermaid flowchart for one join key's propagation across the tables that carry it."""
    tables = key_tables(key)
    es = sorted({(f, t) for (f, t, _b) in edges() if f in tables and t in tables and f != t})
    lines = [f"### `{key}` field flow", "", "```mermaid", "flowchart LR"]
    for t in sorted(tables):
        lines.append(f"    {_node(t)}[{t}]")
    for f, t in es:
        lines.append(f"    {_node(f)} --> {_node(t)}")
    lines += ["```", ""]
    return "\n".join(lines)


def render() -> str:
    parts = [
        "# QRP join-key field flow (generated)",
        "",
        "_Auto-generated by `lineage.diagram` — the free substitute for the Dagster+ column-",
        "lineage view. Each flowchart shows how a join key propagates across the tables that",
        "carry it (edges = declared + auto-derived transform + FK referential). Regenerate with_",
        "`uv run python -m lineage.diagram`.",
        "",
        "> Note: only edges where **both** endpoints carry the key are shown — a transform that",
        "> drops/renames the key terminates the flow, so absence of an edge here is not absence of",
        "> lineage (see the full Dagster asset graph for that).",
        "",
    ]
    parts += [flowchart(k) for k in _KEYS]
    return "\n".join(parts)


def write() -> str:
    out_dir = Path(__file__).resolve().parents[2] / "docs"  # packages/lineage/docs
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "field-flow.md"
    path.write_text(render(), encoding="utf-8")
    return str(path)


if __name__ == "__main__":
    print("wrote", write())
